const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const targetDir = path.resolve(__dirname, '../gallery-frontend/src/wasm');
const pkgDir = path.resolve(__dirname, 'pkg');

console.log('Building WASM...');
try {
    // Execute wasm-pack build
    execSync('wasm-pack build --target web', { stdio: 'inherit', cwd: __dirname });
} catch (e) {
    console.error('WASM build failed:', e.message);
    process.exit(1);
}

console.log('Copying files to frontend...');
if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
}

if (fs.existsSync(pkgDir)) {
    const files = fs.readdirSync(pkgDir);
    let copiedCount = 0;
    
    files.forEach(file => {
        // Copy .js, .wasm, and .d.ts files
        // Exclude package.json and .gitignore which are generated by wasm-pack but not needed in frontend
        if ((file.endsWith('.js') || file.endsWith('.wasm') || file.endsWith('.d.ts')) && file !== 'package.json') {
             const src = path.join(pkgDir, file);
             const dest = path.join(targetDir, file);
             fs.copyFileSync(src, dest);
             console.log(`✓ Copied ${file}`);
             copiedCount++;
        }
    });
    
    if (copiedCount === 0) {
        console.warn('Warning: No matching files found to copy.');
    } else {
        console.log(`Successfully copied ${copiedCount} files to ${targetDir}`);
    }
} else {
    console.error('Error: pkg directory not found after build.');
    process.exit(1);
}
