name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - feat/docker-hub-3

jobs:
  build-amd64:
    name: Build for AMD64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push AMD64 Image
        run: |
          docker build --build-arg BUILD_TYPE=release -t hsa00000/urocissa:amd64-latest .
          docker push hsa00000/urocissa:amd64-latest

  build-arm64:
    name: Build for ARM64
    runs-on: ubuntu-22.04-arm64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push ARM64 Image
        run: |
          docker build --build-arg BUILD_TYPE=release -t hsa00000/urocissa:arm64-latest .
          docker push hsa00000/urocissa:arm64-latest

  create-manifest:
    name: Create and Push Docker Manifest
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and Push Docker Manifest
        run: |
          docker manifest create hsa00000/urocissa:latest \
            hsa00000/urocissa:amd64-latest \
            hsa00000/urocissa:arm64-latest

          docker manifest push hsa00000/urocissa:latest
