name: Manage Dev-Exclusive Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  manage-dev-files:
    runs-on: ubuntu-latest
    env:
      DEV_EXCLUSIVE_FILES: "cleanup.sh"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the entire history to ensure the main branch is available

      - name: Fetch main branch
        run: |
          git fetch origin main  # Ensure the main branch is available locally

      - name: Remove dev-exclusive files in pull requests
        if: github.event_name == 'pull_request'
        run: |
          FOUND_FILES=0
          for file in $DEV_EXCLUSIVE_FILES; do
            if git diff --name-only origin/main...HEAD | grep -q "$file"; then
              echo "Removing $file from PR..."
              git restore --staged "$file" || true
              git checkout "$file" || true
              FOUND_FILES=1
            fi
          done
          if [ "$FOUND_FILES" -eq 1 ]; then
            git commit -m "Remove dev-exclusive files from PR" || echo "No changes to commit"
            git push || echo "No changes to push"
          fi

      - name: Block dev-exclusive files on push to main
        if: github.event_name == 'push'
        run: |
          for file in $DEV_EXCLUSIVE_FILES; do
            if git diff --name-only HEAD~1 HEAD | grep -q "$file"; then
              echo "Error: $file cannot be pushed to main."
              exit 1
            fi
          done
